### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hg668zzx** [liquidhelium/mid2json.py#1]
Last login: Sun Jan 29 14:32:44 on ttys001
macintosh@macbook-air ~ % python3 /Users/macintosh/Downloads/mid2json.py-main/mid2json.py
Traceback (most recent call last):
  File "/Users/macintosh/Downloads/mid2json.py-main/mid2json.py", line 12, in <module>
    def trySerialize(obj: Any) -> typing.Union[dict[Any], Any]:
TypeError: 'type' object is not subscriptable
macintosh@macbook-air ~ % python3 /Users/macintosh/Downloads/mid2json.py-main/mid2json.py
Traceback (most recent call last):
  File "/Users/macintosh/Downloads/mid2json.py-main/mid2json.py", line 12, in <module>
    def trySerialize(obj: Any) -> typing.Union[dict[Any], Any]:
TypeError: 'type' object is not subscriptable
macintosh@macbook-air ~ % 

<img width="579" alt="截屏2023-01-29 14 59 41" src="https://user-images.githubusercontent.com/87606295/215310495-0ff5b21b-e747-4187-9c4e-db15ec98d6a0.png">
 python version 3.7

**Comment by liquidhelium** [comment]
我这有类型注解，低版本py可能运行不了（
